# Generated by Django 3.2.25 on 2025-06-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transition',
            name='logical_type',
            field=models.CharField(default='OR', max_length=10),
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='partial_approvals',
            field=models.JSONField(default=dict),
        ),
    ]
